In [43]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [44]:
path = 'https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/wdbc.data'

In [45]:
df = pd.read_csv(path, header = None)

In [46]:
df.head() # 2~31번 조직을 검사한 데이터 값

0  1      2      3       4       5        6        7       8   \
0    842302  M  17.99  10.38  122.80  1001.0  0.11840  0.27760  0.3001   
1    842517  M  20.57  17.77  132.90  1326.0  0.08474  0.07864  0.0869   
2  84300903  M  19.69  21.25  130.00  1203.0  0.10960  0.15990  0.1974   
3  84348301  M  11.42  20.38   77.58   386.1  0.14250  0.28390  0.2414   
4  84358402  M  20.29  14.34  135.10  1297.0  0.10030  0.13280  0.1980   

        9   ...     22     23      24      25      26      27      28      29  \
0  0.14710  ...  25.38  17.33  184.60  2019.0  0.1622  0.6656  0.7119  0.2654   
1  0.07017  ...  24.99  23.41  158.80  1956.0  0.1238  0.1866  0.2416  0.1860   
2  0.12790  ...  23.57  25.53  152.50  1709.0  0.1444  0.4245  0.4504  0.2430   
3  0.10520  ...  14.91  26.50   98.87   567.7  0.2098  0.8663  0.6869  0.2575   
4  0.10430  ...  22.54  16.67  152.20  1575.0  0.1374  0.2050  0.4000  0.1625   

       30       31  
0  0.4601  0.11890  
1  0.2750  0.08902  
2  0.3613  0.08758  
3  0.6638  0.17300  
4  0.2364  0.07678  

[5 rows x 32 columns]

In [47]:
X = df.iloc[:, 2:].values # 특성행렬

In [48]:
y = df.iloc[:,1]

In [49]:
y = np.where(y == 'B', 0, 1) 
# 이진분류 
# positive class(1), 좀 더 중요한(심각한) 클래스 
# negative class(0)

In [50]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,

In [51]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, stratify = y, random_state = 1)

In [52]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import make_pipeline

In [53]:
pipeline = make_pipeline(StandardScaler(), PCA(n_components=2), LogisticRegression(random_state = 1))

In [54]:
pipeline.fit(X_train, y_train) # 위에서 정의한 StandardScaler()에서 표준화를 할거라서 여기선 안해줘도됨

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('pca', PCA(n_components=2)),
                ('logisticregression', LogisticRegression(random_state=1))])

In [55]:
p = pipeline.predict(X_test)

In [56]:
pipeline.score(X_test, y_test)

0.956140350877193

In [57]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, p )#실제값, 예측값 순서대로 인수를 넣는다. 
# 0 -> B, 1 -> M
#0을 0으로 71개 0을 1로 1개 
#1을 0으로 4개 1을 1로 38개 

array([[71,  1],
       [ 4, 38]], dtype=int64)

In [58]:
from sklearn.model_selection import cross_val_score

In [59]:
scores = cross_val_score(estimator = pipeline, X = X_train, y = y_train, cv = 10, n_jobs = -1)

In [60]:
scores # 10겹짜리 스코어가 각각 나옴

array([0.93478261, 0.93478261, 0.95652174, 0.95652174, 0.93478261,
       0.95555556, 0.97777778, 0.93333333, 0.95555556, 0.95555556])

In [63]:
np.mean(scores) # 모든 겹들의 평균 값 

0.9495169082125603

In [64]:
from sklearn.tree import DecisionTreeClassifier

In [70]:
# DecisionTree에서 가장 중요한 모수?  최대깊이 
best_score = 0
for k in range(1, 11):
    scores = cross_val_score(estimator=DecisionTreeClassifier(max_depth=k, random_state = 1), X = X_train, y = y_train, cv = 5, n_jobs = -1)
    print(k, np.mean(scores))
    if(np.mean(scores) > best_score):
        best_score = np.mean(scores)
        best_parameter = {'max_depth':k} # 딕셔너리로 찝어놔주면 좋음 

1 0.8813186813186814
2 0.9318681318681319
3 0.9296703296703297
4 0.9406593406593406
5 0.9384615384615385
6 0.9362637362637363
7 0.9406593406593406
8 0.9406593406593406
9 0.9406593406593406
10 0.9406593406593406


In [71]:
print(best_score)
print(best_parameter)

0.9406593406593406
{'max_depth': 4}


In [72]:
best_tree = DecisionTreeClassifier(**best_parameter)

In [73]:
best_tree.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=4)

In [74]:
best_tree.score(X_test, y_test)

0.9210526315789473

In [75]:
from sklearn.model_selection import GridSearchCV


In [76]:
my_grid = {'max_depth' : range(1, 11)}

In [77]:
gscv = GridSearchCV(estimator=DecisionTreeClassifier(random_state=1), param_grid=my_grid, scoring='accuracy', cv = 5, n_jobs = -1)

In [78]:
gscv.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(random_state=1), n_jobs=-1,
             param_grid={'max_depth': range(1, 11)}, scoring='accuracy')

In [79]:
gscv.best_score_

0.9406593406593406

In [80]:
gscv.best_params_

{'max_depth': 4}

In [81]:
# 유방암 데이터에 대한 SVC 모형 튜닝 

In [82]:
from sklearn.svm import SVC


In [83]:
pipe_svc = make_pipeline(StandardScaler(), SVC(kernel = 'rbf', random_state = 1))

In [84]:
p_list = [0.001, 0.01, 0.1, 1.0, 10.0, 100.0]

In [85]:
param_grid = {'svc__C' : p_list, 'svc__gamma':p_list}

In [86]:
gs = GridSearchCV(estimator=pipe_svc, param_grid = param_grid, scoring = 'accuracy', cv = 5, n_jobs = -1)

In [87]:
gs.fit(X_train, y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('standardscaler', StandardScaler()),
                                       ('svc', SVC(random_state=1))]),
             n_jobs=-1,
             param_grid={'svc__C': [0.001, 0.01, 0.1, 1.0, 10.0, 100.0],
                         'svc__gamma': [0.001, 0.01, 0.1, 1.0, 10.0, 100.0]},
             scoring='accuracy')

In [88]:
print(gs.best_params_)

{'svc__C': 10.0, 'svc__gamma': 0.01}


In [89]:
print(gs.score(X_test, y_test))

0.9736842105263158
